# Permalinks
permalink:           pretty

# Setup
title:               Bryan Irace
tagline:             Mostly coding and writing
url:                 http://irace.me
paginate:            3
baseurl:             ""

# About/contact
author:
  name:              Bryan Irace
  url:               https://twitter.com/irace
  email:             bryan@irace.me

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/irace/irace.github.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
