# Permalinks
permalink: pretty

# Setup
title: Bryan Irace
tagline: Mostly coding and writing
description: I’m Bryan – a software developer from Brooklyn, NY.
url: http://irace.me
paginate: 3
baseurl: ""
analytics_id: UA-22036475-2

author:
  name: Bryan Irace
  url: https://twitter.com/irace
  email: bryan@irace.me

plugins:
  - jekyll-paginate
  - jekyll-feed

github: [metadata]

sass:
  # Where you keep your scss files
  sass_dir: resume/
  # Where SASS should look for other SCSS
  load_paths:
    - node_modules/
