# Permalinks
permalink:           pretty

# Setup
title:               Bryan Irace
tagline:             Mostly coding and writing
description:         Hey, I’m Bryan. I’m a software developer in NYC currently working on building something new.
url:                 http://irace.me
paginate:            3
baseurl:             ""
analytics_id:        UA-22036475-2

# About/contact
author:
  name:              Bryan Irace
  url:               https://twitter.com/irace
  email:             bryan@irace.me

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/irace/irace.github.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
